{{- if .Values.api.ingress.hosts -}}
{{- $v1Networking := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- $fullName := include "sorry-cypress-helm.fullname" . -}}
{{- $servicePort := .Values.api.service.port -}}
{{- if $v1Networking }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  labels:
    {{- include "sorry-cypress-helm.labels" . | nindent 4 }}
    {{- with .Values.api.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- range .Values.api.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $v1Networking }}
          - path: {{ .path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-api
                port:
                  number: {{ $servicePort }}
          {{- else }}
          - path: {{ .path | default "/" }}
            backend:
              serviceName: {{ $fullName }}-api
              servicePort: {{ $servicePort }}
          {{- end }}
    {{- end }}
  {{- end }}