apiVersion: v1
kind: Service
metadata:
  name: {{ include "sorry-cypress-helm.fullname" . }}-api
spec:
  ports:
  - name: "4000"
    port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.port }}
  selector:
    app: {{ include "sorry-cypress-helm.fullname" . }}-api